version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: .docker/next/Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
      DATABASE_URL: postgres://postgres:postgres@db:5432/resume
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
    ports: ["3000:3000"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resume
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - minio_data:/data

  mailhog:
    image: mailhog/mailhog:latest
    ports: ["1025:1025", "8025:8025"]

volumes:
  postgres_data:
  minio_data: