name: Deploy

on:
  push:
    branches: [main]

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build application
        run: pnpm build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push production images
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ github.repository }}/web:${{ github.sha }} \
            --tag ghcr.io/${{ github.repository }}/web:latest \
            --push \
            --build-arg NODE_ENV=production \
            -f apps/web/Dockerfile \
            .
          
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ github.repository }}/api:${{ github.sha }} \
            --tag ghcr.io/${{ github.repository }}/api:latest \
            --push \
            --build-arg NODE_ENV=production \
            -f apps/api/Dockerfile \
            .
      
      # Add deployment steps here based on your infrastructure
      # Examples:
      # - Deploy to Kubernetes
      # - Deploy to AWS ECS
      # - Deploy to Docker Swarm
      # - Trigger webhook for deployment platform